# Generated by Django 4.1.6 on 2023-06-21 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_eventmodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmodel',
            name='expire_time_hours',
            field=models.DateTimeField(null=True),
        ),
    ]
