# Generated by Django 4.1.6 on 2023-06-22 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_eventmodel_expire_time_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmodel',
            name='expire_time_hours',
            field=models.TimeField(null=True),
        ),
    ]
