# Generated by Django 4.1.6 on 2023-06-24 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_eventmodel_time_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmodel',
            name='expire_time',
            field=models.DateField(),
        ),
    ]
