# Generated by Django 4.1.6 on 2023-06-24 18:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_eventmodel_expire_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmodel',
            name='expire_time_hours',
            field=models.TimeField(default=datetime.time(0, 0)),
            preserve_default=False,
        ),
    ]
