# Generated by Django 4.1.6 on 2023-06-24 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_alter_eventmodel_expire_time_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmodel',
            name='cat',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='event', to='events.category'),
        ),
    ]
