# Generated by Django 4.1.1 on 2022-11-09 20:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryStorageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='gallery')),
                ('author', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(3)])),
                ('date', models.DateTimeField(null=True)),
            ],
        ),
    ]
