# Generated by Django 4.1.1 on 2022-11-10 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallerystoragemodel',
            old_name='file',
            new_name='image',
        ),
    ]
