# Generated by Django 4.1.1 on 2022-11-10 17:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_rename_file_gallerystoragemodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallerystoragemodel',
            name='title',
            field=models.CharField(max_length=100, null=True, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
    ]
