# Generated by Django 4.1.1 on 2022-11-05 19:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thoughts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notemodel',
            name='header',
            field=models.CharField(default='Note', max_length=30, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
    ]
