# Generated by Django 4.1.1 on 2022-11-05 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thoughts', '0002_notemodel_header'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notemodel',
            name='author',
        ),
    ]
