# Generated by Django 4.1.1 on 2022-11-06 08:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thoughts', '0003_remove_notemodel_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='notemodel',
            name='author',
            field=models.CharField(max_length=20, null=True, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
    ]
