# Generated by Django 4.1.1 on 2022-11-09 18:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thoughts', '0004_notemodel_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notemodel',
            name='header',
            field=models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
    ]
