# Generated by Django 4.1.6 on 2023-02-19 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_profile', '0010_alter_profilemodel_user'),
        ('thoughts', '0006_remove_notemodel_date_notemodel_time_create_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notemodel',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author', to='my_profile.profilemodel'),
        ),
    ]
