# Generated by Django 4.1.6 on 2023-02-10 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_menu', '0002_sessiontoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SessionToken',
        ),
    ]
