# Generated by Django 4.1.6 on 2023-02-10 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_menu', '0003_delete_sessiontoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vk_auth_token', models.CharField(max_length=255)),
            ],
        ),
    ]
