# Generated by Django 4.1.6 on 2023-02-10 20:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_menu', '0004_sessiontoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessiontoken',
            name='token_creation_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 2, 10, 20, 42, 45, 201934, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
