# Generated by Django 4.1.6 on 2023-02-11 08:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_menu', '0005_sessiontoken_token_creation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessiontoken',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vk_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sessiontoken',
            name='vk_user_id',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
