# Generated by Django 4.1.1 on 2022-11-22 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_profile', '0003_profilemodel_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilemodel',
            name='avatar',
        ),
    ]
