# Generated by Django 4.1.1 on 2022-11-22 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_profile', '0005_profilemodel_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
