# Generated by Django 4.1.1 on 2023-02-02 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_profile', '0006_profilemodel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='last_name',
            field=models.CharField(blank=True, default='#2', max_length=20),
        ),
    ]
