# Generated by Django 4.1.6 on 2023-02-17 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_profile', '0007_alter_profilemodel_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='last_name',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
