# Generated by Django 4.1.6 on 2023-02-23 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_profile', '0011_alter_profilemodel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='avatar',
            field=models.ImageField(upload_to='avatars'),
        ),
    ]
