# Generated by Django 4.1.6 on 2023-02-24 21:23

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_profile', '0012_alter_profilemodel_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='avatar',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(base_url='/my-gallery/avatars/', location='C:\\myBestDjangoProjects\\broccoli\\uploads\\avatars'), upload_to='avatars/'),
        ),
    ]
